# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm build
    - name: Deploy to Server
      uses: nogsantos/scp-deploy@master
      with:
        src: ./_site/*
        host: ${{ secrets.REMOTE_HOST }}
        remote: ${{ secrets.REMOTE_TARGET }}
        port: ${{ secrets.REMOTE_PORT }}
        user: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
